global: {}

ibm-platform-navigator-instance:
  ibmplatformnavigator:
    name: integration-navigator
    spec:
      license:
        accept: true
        license: L-RJON-C7QG3S
      mqDashboard: true
      version: 2021.4.1
      replicas: 2   